### PR TITLE
add two more validators

### PR DESCRIPTION
**Pull request by tugytur**
additional two validtors

3) 5HdxB6kQRvk1xMSc4RYE7yGXLVBih6uYFANtKfeKTmh1q3wv
4) 5GTyU9BSt5vRSFKxAS2qH5Yj86JbgbrNVGtnxDJDLyzUKJbd

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@tugytur validators already funded, ready for bonding

**Comment by tugytur** [comment]
@educlerici-zondax thanks, I've created the bond and set the session-key

**Comment by educlerici-zondax** [comment]
Done, lets wait for the next era so the validators can be in the active set

**Review by educlerici-zondax — APPROVED** [review]
Already on the active set

**Pull request merged**
