### PR TITLE
Add openbitlab validator addresses

### PR DESCRIPTION
**Pull request by openbitlab2**
This PR will add openbitlab validators to Paseo

### CODE REVIEW

**Comment by al3mart** [comment]
Hello @openbitlab2!

Could you please add a comment with the proof of ownership of the Polkadot stash account `13pYWKctR5s8vQuyZt3pxQXue4SRH9coyAS9S9z5HtogAnhs` ? 

The proxy of that account would also be something we can double check.

As per the onboarding instructions you can sign the message `PASEO` in, for instance, using polkadot.js apps - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fpolkadot#/signing

**Comment by openbitlab2** [comment]
Hi @al3mart, here is our signature:
0x62cb6a0871d5a2fc6ac95dfef04c9a25996f470cba04d3c322e2bede2a71cd767161d721a9f6a15055b8169d89bd5383a3af92fb27fbb30f5a0ff1ea78ebfc8c

Let me know if you have any other questions

**Comment by al3mart** [comment]
Awesome! Thank you very much for the quick response.

You should be able to bond now. We will proceed with the nominations once that is done :)

**Comment by openbitlab2** [comment]
> Awesome! Thank you very much for the quick response.
> 
> You should be able to bond now. We will proceed with the nominations once that is done :)

Thanks, bonded funds for both validators

**Review by al3mart — APPROVED** [review]

**Pull request merged**
