### PR TITLE
Onboard bestvalidator paseo validator and asset-hub collator

### PR DESCRIPTION
**Pull request by mosonyi**
Hi, Please welcome my onboarding to paseo validator and assethub collator. Thanks

### CODE REVIEW

**Comment by hbulgarini** [comment]
Thanks for your submission @mosonyi ! At the moment we have already covered the two sits available for the assethub collators. We will let you know for sure when we open the room for more system chain collators. For the moment could you please remove the assethub section?

Also, did you have the chance to read the application document? Please refer to the criteria section to be eligible to run validators and let us know if you meet them:

https://github.com/paseo-network/paseo-action-submission/blob/main/pas/PAS-1-onboard_infrastructure_providers.md

**Comment by hbulgarini** [comment]
> Hi @hbulgarini , I checked the criteria, and I think it is ready to go.

As the document says, a proof that you are part of 1KV or that you are running a production system chain collator has to be shared here in order to onboard your validator. I would appreciate sharing those with the signed message as the documentation requests.

**Comment by mosonyi** [comment]
> > Hi @hbulgarini , I checked the criteria, and I think it is ready to go.
> 
> As the document says, a proof that you are part of 1KV or that you are running a production system chain collator has to be shared here in order to onboard your validator. I would appreciate sharing those with the signed message as the documentation requests.

Certainly:
* Polkadot validator: https://polkadot.w3f.community/candidate/1123RekaPHgWaPL5v9qfsikRemeZdYC4tvKXYuLXwhfT3NKy
* System chain collator on collectives: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.dotters.network%2Fcollectives-polkadot#/collators
* Signed message: `0xdeee57ca407536c7a682fe552552e6f4017649247b11f705952b6fd37c9c8c390628a044f3cdda28394c22150673fd0c8605fc4a525392c75042cdda6e2bb587`

**Comment by mosonyi** [comment]
Hi @hbulgarini , I am unsure if you can take 2 validator requests from me. I already added it, if you say I can remove it.

**Comment by al3mart** [comment]
Hello @mosonyi, you can bond now!
Once that is done we will proceed with the nominations.

Thanks.

**Comment by mosonyi** [comment]
Hi @hbulgarini , amounts are bonded. Thanks

**Comment by al3mart** [comment]
Hey @mosonyi everything is lookig great. I was checking the signature, could you please let me know what is the account you have used to sign the message ? I can see a few different accounts here: https://polkadot.w3f.community/candidate/1123RekaPHgWaPL5v9qfsikRemeZdYC4tvKXYuLXwhfT3NKy

**Review by al3mart — APPROVED** [review]

**Comment by mosonyi** [comment]
> Hey @mosonyi everything is lookig great. I was checking the signature, could you please let me know what is the account you have used to sign the message ? I can see a few different accounts here: https://polkadot.w3f.community/candidate/1123RekaPHgWaPL5v9qfsikRemeZdYC4tvKXYuLXwhfT3NKy

Hi @al3mart , you want me to sign the message with that account? 
I think I signed with a new one I created for paseo. 5GCRBFeiJxU6xtqpHyWiwq1Nww47peRK1FxgeNA1eXRwGqkG

**Pull request merged**
