### PR TITLE
add ExtraCoin/06

### PR DESCRIPTION
**Pull request by yaronski**
Following the request to add one additional validator #6 is up and running & has its identity set.

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@yaronski stash funded, ready for bonding!

**Comment by yaronski** [comment]
@educlerici-zondax thanks! bonded.

**Comment by educlerici-zondax** [comment]
nominated, waiting some eras to be in the active set

**Review by educlerici-zondax — APPROVED** [review]
ready in the active set

**Pull request merged**
