### PR TITLE
Update openbitlab.yml - add 5th Paseo validator

### PR DESCRIPTION
**Pull request by openbitlab2**
Adding 5th validator to offer 40 cores in Paseo

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@openbitlab2 funded and ready for bonding!

**Comment by openbitlab2** [comment]
> @openbitlab2 funded and ready for bonding!

Bonded! Thanks

**Comment by educlerici-zondax** [comment]
waiting for a few eras to be in the active set!

**Comment by educlerici-zondax** [comment]
already in the active set!

**Review by educlerici-zondax — APPROVED** [review]

**Pull request merged**
