### PR TITLE
Add 3 parity validators

### PR DESCRIPTION
**Pull request by PierreBesson**
Added 3 additional Parity managed Paseo validators

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@PierreBesson stash funded! can you please check and bond?

**Comment by educlerici-zondax** [comment]
@PierreBesson ready for bonding. sorry the delay, i had some issues with the transactions

**Comment by educlerici-zondax** [comment]
@PierreBesson have you bonded?

**Comment by PierreBesson** [comment]
I have just bonded and activated our validators.

**Comment by educlerici-zondax** [comment]
done! waiting for a few eras to be in the active set

**Review by educlerici-zondax — APPROVED** [review]
ready in the active set

**Pull request merged**
