### PR TITLE
Update ParaNodes.yml

### PR DESCRIPTION
**Pull request by paradox-tt**
This PR seeks to amend the name of my second validator and seek to induct two more validators, 03 and 04.  The validators have keys applied but require additional funds to declare the validation intent.

When funds are sent I'll declare intent.  Thank you for your support.

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@paradox-tt already funded, waiting for bonding!

**Comment by paradox-tt** [comment]
Fast movements!
Bonded.

**Comment by educlerici-zondax** [comment]
Thanks! we are waiting for a new era so both can be in the active set

**Review by educlerici-zondax — APPROVED** [review]
already in the active set

**Pull request merged**
