### PR TITLE
Gatotech: update old & spin 5th validator

### PR DESCRIPTION
**Pull request by miloskriz**
Dear team, hello!

This proposal updates the display names and stashes' encoding of current validators, and add the fifth Paseo validator provided by Gatotech.

Regarding the fifth stash, Could you please airdrop some additional 66K PAS to complete the required stake?

Many thanks!!

Best regards

**_Milos_**

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@miloskriz already sent those pas to the stash! let me know when you bond please

**Comment by miloskriz** [comment]
thanks a lot @educlerici-zondax !!

I can confirm validator is bonded and waiting!

Cheers! 🥳 

**_Milos_**

**Comment by educlerici-zondax** [comment]
already nominated, just waiting a few eras to be in the active set 💪

**Review by educlerici-zondax — APPROVED** [review]
ready in the active set! 💪

**Pull request merged**
