### PR TITLE
Update ParaNodes.yml

### PR DESCRIPTION
**Pull request by paradox-tt**
Applying for sixth node as requested in the main channel

### CODE REVIEW

**Comment by paradox-tt** [comment]
Just a reminder, let me know if you don't require the node anymore and I can wind it down.

**Comment by paradox-tt** [comment]
I'm only seeing 99 PAS on `15ca1Ui8a2YjZdDekDxtwcqt66ZdCwaNa377AxYBhVXGVUgP`

**Comment by educlerici-zondax** [comment]
@paradox-tt sorry, my bad. now yes you can bond!

**Comment by paradox-tt** [comment]
Bonded and Validation intent set

**Comment by educlerici-zondax** [comment]
@paradox-tt ready in the active set, sorry the delay, i was having some issues to nominate

**Review by educlerici-zondax — APPROVED** [review]

**Pull request merged**
