### PR TITLE
Update gatotech.yml

### PR DESCRIPTION
**Pull request by miloskriz**
Dear team, hello!

Please consider the below request to add our validator nodes No.3 & No.4 to the active set.

From these two, please note that No.3 already has enough stake to validate, but please add some funds to No.4:

- 5HgatoAHMHZUEyUgbchcXexuGYs5EWehBymvg8vQpRZFdY8E

Finally, please note that both of them will be operating in San Jose de Costa Rica, to provide additional geographic diversification.

Many thanks!!

Best regards

**_Milos_**

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@miloskriz done! stash funded, let me know please when you bond so i can nominate you

**Comment by miloskriz** [comment]
Dear @educlerici-zondax, hello !

Many thanks for the funding!...

unfortunately,  the transfer failed :pensive:

https://paseo.subscan.io/extrinsic/1883114-2

Can you please retry it?

Many thanks!

**_Milos_**

**Comment by educlerici-zondax** [comment]
@miloskriz yes, sorry for the issue and delay, i was dealing with the transactions but it seems to be solved. please confirm 🙏

**Comment by miloskriz** [comment]
hello @educlerici-zondax !

It worked a charm!!

I can confirm the stake is bonded and validation intent is configured on-chain for both nodes!

Many thanks!

**_Milos_**

**Review by educlerici-zondax — APPROVED** [review]
great! ready on the active set!

**Comment by miloskriz** [comment]
Many thanks @educlerici-zondax 

One question... will you also nominate the new validators?

I can see the new validators are still being listed under `active` and `waiting` at the same time.. it seems odd, doesn't it?

Please advise..

Best regards!!

**_Milos_**

**Pull request merged**
