### PR TITLE
Add PAS3 and PAS4 validators for Bestvalidator

### PR DESCRIPTION
**Pull request by mosonyi**
Please accept my to new validators

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@mosonyi 
Stash funded, please feel free to proceed with bonding.

**Comment by educlerici-zondax** [comment]
@mosonyi 
have you bonded?

**Comment by mosonyi** [comment]
@educlerici-zondax Hi, I got the PAS on my PAS4 account. -> bonded
could you please fund the 5DJb44caCLAgfgxBDcP3Q5GQ4SGpMHAGyrXPyMnz6FrYSXED as well?
Thanks

**Comment by educlerici-zondax** [comment]
@mosonyi done!

**Comment by mosonyi** [comment]
thanks @educlerici-zondax . done.

**Comment by educlerici-zondax** [comment]
@mosonyi 
Nominated. It should onboard in the active set in the coming eras, max 2.

**Review by educlerici-zondax — APPROVED** [review]

**Pull request merged**
