### PR TITLE
add validator 6 for Sik | crifferent.de

### PR DESCRIPTION
**Pull request by SimonKraus**
Validator is ready, identity set, please send funds to 1Eu3wjXT7bBeYw3YqrDvudseugJbybEDhBanGWMaBcPKSqF

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@SimonKraus ready for bonding!

**Comment by SimonKraus** [comment]
@educlerici-zondax  bonded, started validation.

**Comment by educlerici-zondax** [comment]
nominated, waiting a few eras to be in the active set!

**Review by educlerici-zondax — APPROVED** [review]
ready in the active set

**Pull request merged**
