### PR TITLE
Onboard Paseo Staker Space Validator

### PR DESCRIPTION
**Pull request by Suleymann85**
Here is our on boarding registration. Thanks

### CODE REVIEW

**Comment by al3mart** [comment]
Hello @Suleymann85 

You can now bond! We will proceed with nominations once that is done.

**Comment by al3mart** [comment]
Could you please add a comment with the proof of ownership of the Polkadot stash account `1NqVmUJCyaj5yZ9jp7ZZa58hbUx2QaBZ4eSCu9bqAdZXgAm` ?

A proxy of that account would also be something we can double check.

As per the onboarding instructions you can sign the message `PASEO`, for instance, using polkadot.js apps - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fpolkadot#/signing

**Comment by Suleymann85** [comment]
> 1NqVmUJCyaj5yZ9jp7ZZa58hbUx2QaBZ4eSCu9bqAdZXgAm

Hi @al3mart,

Please see our signature:
`0x880c2bc2a577a7ec8aebb11bc2e524d047e279ef2a827ad2fbbf0211f922e84e8eb573a218e8751f541abe692d8af28bbd31cec4ebe19b403f29fbf75327ae8c`

**Comment by al3mart** [comment]
image
I am not able to verify the signature. I have tried checking with the account on the capture, with its parent account and the proxy for the parent account.

None of them gave me a green check.

Could you help me identify the account used to sign the message ?

**Comment by al3mart** [comment]
It looks like I copied a space in the signature message. Thanks for the heads up @Suleymann85!

Everything is looking good.

image

You can now bond :+1:

**Review by al3mart — APPROVED** [review]

**Pull request merged**
