### PR TITLE
Create 🐟bluefintuna🐟.yml

### PR DESCRIPTION
**Pull request by tunkas**
Please add my two validators to Paseo testnet.
Thank you!

### CODE REVIEW

**Comment by tunkas** [comment]
Hi!
I am a participant of both 1KV programs on Kusama and Polkadot. 
Furthermore, I am a collator on the Kusama AssetHub and BridgeHub system parachains, as well as on Polkdot AssetHub, Collectives, and BridgeHub system parachains.

**Comment by tunkas** [comment]
Hi!
Just to follow up - is anything else needed or expected from me in order to move forward?
Thanks!
A

**Comment by educlerici-zondax** [comment]
Hi @tunkas, apologies for the delay in getting back to you. We've reached our capacity for validator slots sooner than anticipated, and unfortunately, all slots are currently filled. We're looking to expand our capacity and onboard additional validators at the earliest opportunity. Rest assured, you're at the top of our list for the next available slot. Thank you for your understanding and patience.

**Comment by tunkas** [comment]
I understand, thank you for the update.
Is there any (rough) timeframe for future onboarding?
Thanks!
A

**Comment by educlerici-zondax** [comment]
@tunkas not at this moment but we will work harder to have them as soon as possible

**Comment by tunkas** [comment]
Thank you!
A

**Comment by tunkas** [comment]
Hmm, how come you closed my pull request? 
Can't you just leave it open until it can be completed, so we don't have to go through all the step all over again?
Thanks!
A

**Comment by tunkas** [comment]
Also, I see LuckyFriday applied for their spot after me, but seems they
will be onboarded.
Would you be so kind to explain why is this so?
Thank you!
A

pon, 8. tra 2024. u 21:36 educlerici-zondax ***@***.***>
napisao je:

**Comment by itsbirdo** [comment]
Hi @tunkas thanks for your request and enthusiasm around the Paseo testnet :)
At this point we have selected providers based on their previous track record, the order in which they applied and how well the team is known to us (the maintainers). 

In this instance we have prioritised the Lucky Friday team over BlueFinTune which I can appreciate is frustrating for yourself and the team, however as stated above, we will have future slots opening up and your team will be at the top of the list for when we onboard more validators.

**Comment by tunkas** [comment]
Hi!
Thank you for your clear information, I fully understand.

Will there be some kind of notice given when the new onboarding wave
commences?

A

**Comment by itsbirdo** [comment]
Yes I recommend joining the element room -> https://matrix.to/#/#paseo-testnet-support:parity.io
or setting notifications on the discord channel in the Polkadot discord server -> https://discord.gg/polkadot
or the twitter account -> https://twitter.com/PaseoNetwork

we will announce it here when we are ready to move forward with adding new validators

**Comment by tunkas** [comment]
I'm part of the element group, thank you!

A

**Pull request closed without merging**
