### PR TITLE
Update CoinStudio.yml Add 6th validator

### PR DESCRIPTION
**Pull request by CoinStudioDOT**

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@CoinStudioDOT stash funded, ready for bond!

**Comment by educlerici-zondax** [comment]
@CoinStudioDOT let me know when you bond so i can nominate you please 🙏

**Comment by CoinStudioDOT** [comment]
Bonded and ready

**Comment by educlerici-zondax** [comment]
nominated, waiting some eras to be in the active set 💪

**Review by educlerici-zondax — APPROVED** [review]

**Pull request merged**
