### PR TITLE
New Validator: New file validorange.yml

### PR DESCRIPTION
**Pull request by validorange**
This is my submission to operate a validator on Paseo.

Polkadot 1KV address: 1D51dxpuGv1mWxstx7ERWyEWieLHSeQ8NBVX7VxkxT5PuKg

### CODE REVIEW

**Comment by validorange** [comment]
0xfc435ea0bdac464a660e2fc20963ad8a140a18407da71f927717903535801558e58dc86d3f9fac18f6929053cece617a103fe1e619e8147d941b45572257a383

**Comment by validorange** [comment]
Previous comment is signed with my POlkadot proxy (1srcFWVcPn2oXEKuddMMTGCLQMDdRqxKKo9qpFTi8PA7NW1). The Polkadot stash account is a hardware wallet that does not support signing. If you prefer I can also sign with either of my Kusama stash accounts.

**Comment by al3mart** [comment]
Awesome! It looks good.

That is asked as a way for us to confirm identities and ownership of the keys. I hope the process doesn't come through as cumbersome. You are one of the first trying it, so I'd personally love to hear your thoughts.

We believe this is one of the strongest assurances we can get in terms of proving that the person requesting running a validator is legitimately owner of the keys that fulfill the criteria.

**Comment by validorange** [comment]
The process is pretty simple, but at first I didn't really understand the instructions around signing since it's not something I've done before. If you're willing to accept a signature from either the proxy or the stash, that's helpful, since in my case I couldn't sign with a Ledger wallet (the stash).

I might write the instructions something like this:

"To prove ownership of your Polkadot 1KV validator, please sign the text "PASEO" with your validator's stash account or proxy account, using a tool such as Polkadot.js (under Developer -> Sign and verify) or Subkey, then submit the signature as a comment on your pull request."

**Comment by al3mart** [comment]
That's great feedback, will make some changes to the instructions so they read a bit friendlier. Thanks.

**Review by hbulgarini — APPROVED** [review]

**Review by al3mart — APPROVED** [review]

**Pull request merged**
