### PR TITLE
Additional Dwellir validators

### PR DESCRIPTION
**Pull request by abbaahmad**

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@abbaahmad already sent to those stashes. please let us know when you bond

**Comment by abbaahmad** [comment]
> @abbaahmad already sent to those stashes. please let us know when you bond

Hi. We've bonded the validators. Thanks

**Comment by educlerici-zondax** [comment]
@abbaahmad it seems that you have bonded but you are missing to do the session.set_keys and staking.validate

**Comment by abbaahmad** [comment]
> @abbaahmad it seems that you have bonded but you are missing to do the session.set_keys and staking.validate

Apologies for the delay. The missing steps have been completed

**Review by educlerici-zondax — APPROVED** [review]
already in the active set

**Pull request merged**
