### PR TITLE
Add PAS5 validators for Bestvalidator

### PR DESCRIPTION
**Pull request by mosonyi**
Please accept my new validator

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@mosonyi ready for bonding!

**Comment by mosonyi** [comment]
@educlerici-zondax done, thanks

**Comment by educlerici-zondax** [comment]
Nominated, waiting for next eras to be in the active set

**Comment by educlerici-zondax** [comment]
Done! already in the active set!

**Review by educlerici-zondax — APPROVED** [review]

**Pull request merged**
