### PR TITLE
Adding StakingLand Validators

### PR DESCRIPTION
**Pull request by ecov773**
This PR adds in the validators of StakingLand
I create this PR as commented with @al3mart 

LFG!

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@ecov773 
already transfered to the stash you sent
feel free to bond please! 

also, can you please add your identity to the stash?

**Comment by ecov773** [comment]
Thanks @educlerici-zondax, can you please also send it to my first two stash accounts? Then I can also bond there. Thanks!

**Comment by ecov773** [comment]
I've set the identity and bonded for 3 and 4. Just missing to bond for 1 and 2 (5HpC6p5y3MyNZWbjE9vhYRafVR56tFqgkLFWLAcWcWUWd6cF and 5DaVS2qqHgZEkZVam6JvFEPu9AhVmUaDPjtT9vibCR1kQ3oa) once I receive the tokens.
Thanks

**Comment by educlerici-zondax** [comment]
Hi @ecov773 , sorry i confused and I thought that you were currently in the active set , currently we are not accepting new validator submissions, as we're focusing on adding new stashes for validators already in the active set. However, we will tag this PR as 'pending' and queue it for inclusion once we resume accepting new validators. 

You can find more information about the requirements to become a validator in our Paseo GitHub repository here.
https://github.com/paseo-network/support/wiki/How-to-Setup-a-Node-Validator%3F


cc @itsbirdo

**Comment by educlerici-zondax** [comment]
@ecov773 we will continue with the nomination for your validators #3 and #4. you will see them in the active set soon. We will touch base with you for the turn of the #1 and #2 validators.
Thanks!

**Comment by ecov773** [comment]
Hi @educlerici-zondax,
Sorry, I did not understand the second part of your message. So #3 and #4 will be active soon, and #1 and #2 will be down? Or what did you mean?

Thanks

**Review by educlerici-zondax — APPROVED** [review]
pas3 and pas4 already in the active set running!

**Pull request merged**
