### PR TITLE
Create luckyfriday.yml

### PR DESCRIPTION
**Pull request by mchaffee**

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
Thanks @mchaffee !
You can now bond. We will proceed with nominations as soon as that is done.

**Comment by educlerici-zondax** [comment]
@mchaffee just as a friendly reminder. Have you bonded?

**Comment by mchaffee** [comment]
Yes, it has been bonded.

- m

**Comment by al3mart** [comment]
Nominations updated :+1: Your validator should enter the active set in the coming eras.

**Review by al3mart — APPROVED** [review]

**Pull request merged**
