### PR TITLE
add openbitlab validator

### PR DESCRIPTION
**Pull request by openbitlab2**
Add 6th openbitlab validator

`5DaLaT5mv4hBLYSMbAvDWfLobM4WMiiDH5iqGfEGniMnaAs7`

### CODE REVIEW

**Comment by educlerici-zondax** [comment]
@openbitlab2 stash funded, ready for bonding!

**Comment by openbitlab2** [comment]
> @openbitlab2 stash funded, ready for bonding!

Tokens bonded! Thanks

**Comment by educlerici-zondax** [comment]
nominated! waiting to be in the active set soon

**Review by educlerici-zondax — APPROVED** [review]
ready in the active set

**Pull request merged**
