### PR TITLE
Create paseo-validators/active/metaspan.yml

### PR DESCRIPTION
**Pull request by dcolley**
Add details for metaspan validator

### CODE REVIEW

**Comment by al3mart** [comment]
Please, proceed with bonding :)

**Review by al3mart — APPROVED** [review]

**Comment by hbulgarini** [comment]
@dcolley could you please remove the asset hubs collator from this PR? thanks!

**Comment by dcolley** [comment]
@hbulgarini ok, that's done now

**Review by hbulgarini — APPROVED** [review]

**Review by al3mart — APPROVED** [review]

**Comment by hbulgarini** [comment]
As this branch has some conflicts, the metaspan.yml file was included in the https://github.com/paseo-network/paseo-action-submission/pull/74 to make it easier.

**Pull request closed without merging**
