### PR TITLE
Update Mile.yml

### PR DESCRIPTION
**Pull request by matherceg**
Add Mile/Charlie and Mile/Delta validators to the Paseo validator list

### CODE REVIEW

**Comment by matherceg** [comment]
I would like to add:
Mile/Charlie 
`5Gjo7xaoQJVyPpa9zWGy8Qt8VaLpPWH3sRKJK6R6c85v4zeL`

and Mile/Delta 
`5FsRLEAeuSHcrQ8SqLK2uc1GA6ap1m1x4NL99k8gVTJG9wnb`

validators to the Paseo validator list.

**Comment by educlerici-zondax** [comment]
@matherceg validators funded, ready for bonding

**Comment by educlerici-zondax** [comment]
Done, already nominated, lets wait for the nexts era to be in the active list

**Review by educlerici-zondax — APPROVED** [review]
done!, already in the active set

**Pull request merged**
