### PR TITLE
Create ParaNodes.yml

### PR DESCRIPTION
**Pull request by paradox-tt**
Added validator 1, will add validator 2 within 24hrs.

### CODE REVIEW

**Comment by paradox-tt** [comment]
Just following up, is there anything I need to do further to have my second validator on-boarded?

**Comment by educlerici-zondax** [comment]
Thanks @paradox-tt and sorry for the delay 🙏 
You can now bond. We will proceed with nomination as soon as that is done.

**Comment by educlerici-zondax** [comment]
@paradox-tt just as a friendly reminder, have you bonded?

**Comment by paradox-tt** [comment]
Hey,

I'm bonded and switched to validate intent. Validator is in waiting.

Regards,
Will

**Comment by al3mart** [comment]
Nominations updated :+1: Your validator should enter the active set in the coming eras.

**Review by al3mart — APPROVED** [review]

**Pull request merged**
